### ISSUE TITLE
WhatCrypt for Androi



### ISSUE THREAD

**Issue by mishamihail** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#15]
**Hexdump of your key file**
Add the hexdump of your key file here

**Hexdump of the encrypted DB
Add the hexdump of the first 256 bytes of your DB here.

**Screenshots**

**Program output using -v and -f**
 

**Additional context**

**Comment by ElDavoo** [comment]
This project is not affiliated with WhatCrypt.
