### ISSUE TITLE
error: argument encrypted: can't open 'msgstore.db.crypt15

### ISSUE THREAD

**Issue by Mrakobes666** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#19]
error: argument encrypted: can't open 'msgstore.db.crypt15': [Errno 2] No such file or directory: 'msgstore.db.crypt15'

the fact is that I am not trying version 15 - I put 14, but the script does not see it

**Comment by Mrakobes666** [comment]
decrypt14_15.py [-h] [-f] [-nm] [-bs BUFFER_SIZE] [-ng] [-np] [-ivo IV_OFFSET] [-do DATA_OFFSET] [-v] [keyfile] [encrypted] [decrypted]

**Comment by ElDavoo** [comment]
yeah, that's the command line. You need to give the keyfile, the encrypted file and the decrypted file **in order**.

**Comment by Mrakobes666** [comment]
python ./decrypt14_15.py ./key ./msgstore.db.crypt14 ./msgstore.db
[I] Crypt12/14 key loaded
[I] Database header parsed
[I] Done


its work!

**Comment by ElDavoo** [comment]
Happy to know that! Please close the issue if there are no problems left
