### ISSUE TITLE
"source venv/bin/activate" dosnt work

### ISSUE THREAD

**Issue by Conan179** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#27]
Hi, the point "source venv/bin/activate" on the manuel are not worikng on my win 10 21h2.
The error massage is:
PS C:\Users\Con\WhatsApp-Crypt14-Crypt15-Decrypter> source venv/bin/activate
source : Die Benennung "source" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines
ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern
enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ source venv/bin/activate
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ElDavoo** [comment]
The quickstart block has been made so you copy-paste the entire block.

**Comment by Conan179** [comment]
oh im sorry, hadn't seen that it was for different systems.

**Comment by ElDavoo** [comment]
Don't worry, let me know if you have other problems or close this issue, thank you
