### ISSUE TITLE
decrypt the ChatStorage.sqlite.enc

### ISSUE THREAD

**Issue by devops35** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#34]
How do I decrypt the ChatStorage.sqlite.enc file?

**Comment by ElDavoo** [comment]
No idea, this project does not support iOS. 
Take a look at this https://yasoob.me/posts/extracting-whatsapp-messages-from-ios-backup/

**Comment by solywsh** [comment]
Hi, I found that https://yasoob.me/posts/extracting-whatsapp-messages-from-ios-backup/ is just about how to decrypt normal mobile backup files. It mainly tells how to restore ChatStorage.sqlite, which is generated by mobile backup. However, ChatStorage.sqlite.enc is actually generated by icloud backup. The two are not the same.
