### ISSUE TITLE
Jupyter version

### ISSUE THREAD

**Issue by AlePaff** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#41]
Here is a draft i made https://colab.research.google.com/drive/1PxMrEiM0RVjF7roSlSs1bsvqAt9ITpQo?usp=sharing

**Comment by ElDavoo** [comment]
Making it work in google colab/jupyter is actually #5 , as if it was completed it would be a lot easier to import it in a notebook via pip. Appreciating the effort. Improve it and make a pull request

**Comment by ElDavoo** [comment]
Issue closed, but I still think it can be enhanced with #5 , or maybe even better, create a javascript implementation of this program and make an online website for decrypting/encrypting. I leave this task as an exercise for the reader
