### ISSUE TITLE
Keyfile is not a valid Java object

### ISSUE THREAD

**Issue by pepbobmc** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#42]
Program returns the following error

`[F] The keyfile is not a valid Java object: Invalid file magic: 0xefbb`

I made a text file using gedit with the key inside and then renamed it to `encrypted_backup.key`. Is that not right?

Thank you

**Comment by ElDavoo** [comment]
If you're too lazy to do that and you're not using Windows, you can use a shell trick to read the file and use it as it was a parameter:
`python ./decrypt14_15.py $(cat encrypted_backup.key) ./msgstore.db.crypt15 ./msgstore.db`

**Comment by pepbobmc** [comment]
Your second solution worked :) (I had to use `--force` though, do I report that somewhere?) and I am now able to access all my messages with DB Browser for SQLite. Thank you tons :)))

**Comment by ElDavoo** [comment]
> Your second solution worked :) (I had to use `--force` though, do I report that somewhere?) 

Yes. Can you send the full log?

**Comment by pepbobmc** [comment]
How to do so?

**Comment by ElDavoo** [comment]
Copy-paste here

**Comment by pepbobmc** [comment]
It actually worked fine now without `--force` when doing a re-run, so it may have been one of the error-runs where I didn't have all of the packages and I misremembered. Sorry for the confusion!

**Comment by julienthevenoz** [comment]
Hi ! 
I have the same problem as OP. 
But for option 1 : the link you posted [utils/hex_string_to_encrypted_backup_key.py](https://github.com/ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter/blob/main/utils/hex_string_to_encrypted_backup_key.py) seems to not exist anymore
For option 2 : the link you post sends to the readme of your repo, and I cannot find an example of providing the key directly in the command line.

Help ?

**Comment by anairamzap-mobomo** [comment]
Sorry to comment on such an old ticket, but I just stumped into this and I was able to decrypt it using the 64-char long text key like this:

```
wadecrypt $(cat whatsapp_e2e_key.txt) msgstore.db.crypt15 msgstore.db
```
So basically using bash cat to 'read' the key.

**Comment by eduardonunesp** [comment]
@anairamzap-mobomo solution works great, thanks
