### ISSUE TITLE
Unwanted case substitution

### ISSUE THREAD

**Issue by komova-i** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#45]
Hi! After processing the script, the messages change the case to lower case. Is it possible to avoid this? I need the messages in their original form, as the links from the messages don't work after changing the case. Thanks in advance)

**Comment by ElDavoo** [comment]
Hi, the script does not alter the sqlite database in any way.

**Comment by komova-i** [comment]
Are you sure?) But the case is definitely changed to lower case for all data. This may not be intentional, but the script does change the case, you can see for yourself)

**Comment by ElDavoo** [comment]
and you can read the code.

**Comment by ElDavoo** [comment]
You're probably using the sqlite viewer incorrectly
![image](https://user-images.githubusercontent.com/7345120/205354175-b77c50b1-29d9-45c3-a246-707298158627.png)

**Comment by komova-i** [comment]
I open the database via SQlite Studio or upload data via command line shell for SQLite using SELECT. Ok, you've convinced me) I'll check what might be wrong on the sqlite side.
