### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Pandora792** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#48]
I need to decrypt a copy of the local backup of the whatsapp files, these are crypt 15, the thing is i had activated the "encrypt" opition which i didnt rememver having (i dont have any password or the 64 digits). The big issue is that i reinstales the app on other phone (closing the session in the other phone), copy the backup archives in the new phone... But i can access the backup. I know it's possible to decrypt it and restore it, but i dont know how. I really need those chats back on my whatsapps, some of them are a crucial part of a legal issue I have in few months, please, help!

**Comment by ElDavoo** [comment]
First line of Readme:
"Decrypts WhatsApp .crypt14 and .crypt15 files, given the key file or the 64-characters long key."
Without it nothing can be done
