### ISSUE TITLE
Cant decrypt crypt14 after new whastapp update

### ISSUE THREAD

**Issue by zacsan** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#49]
I have been able to decrypt databases before but now i am getting the output below:

**Program output using -v and -f**
[V] Reading keyfile...
[I] Crypt12/14 key loaded
[V] Key(key: hidden , serversalt: hidden , googleid: hidden , key_version: 02 , cipher_version: 0001)
[V] Parsing database header...
[V] WhatsApp version: 2.23.1.76
[V] Your phone number ends with "hidden"
[E] Server salt mismatch: b'{\xa5\n\xc21,"\xcf\x9f>\n\xa6P2\xa1r\xec\x97\xf8U1\xf7S$\xbf\x08\x0e@\xad:\xe2\xef' != b'\x10\x00\xbeK\x1e\x03Q\xee\x91\xd2\xcb*\x02\xc5\n&\x13M\xa2\x8e\xf3\x8f:\x02\xf8\x8b2\x1d=Q\xb4\xc9'
To bypass checks, use the "--force" parameter

**Additional context**
I get an error trying to decrypt. crypt14 db after new whatsapp update
I have replaced what i feel is sensitive info with "hidden"

**Comment by ElDavoo** [comment]
@zacsan did you decrypt it correctly? server salt mismatch means you are trying to decrypt another account's backup

**Comment by zacsan** [comment]
Yes i did. Initially i was getting that error but it resolved on its own.
