### ISSUE TITLE
Cant decrypt14

### ISSUE THREAD

**Issue by bluemooduser** [ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter#53]
I am trying to decrypt latest db14 and is shows:

$ python ./decrypt14_15.py ./key ./msgstore.db.crypt14 ./msgstore.db
[I] Crypt12/14 key loaded
[I] Database header parsed
[I] Done

But i get nothing in the folder. Why is it?
Sorry I am just making a stupid question.

**Comment by ElDavoo** [comment]
you should get a msgstore.db output file with the database

**Comment by ElDavoo** [comment]
closing as no further info sent

**Comment by victorbg84** [comment]
i have this problem to run this command python ./decrypt14_15.py ./key ./msgstore.db.crypt14 ./msgstore.db

The key file specified does not exist.
    If you tried to specify the key directly, note it should be 64 characters long and not 5 characters long.
